ARG BASE_TAG="develop"
ARG BASE_IMAGE="firefox"
FROM kasmweb/$BASE_IMAGE:$BASE_TAG
#ARG BASE_TAG="test"
#ARG BASE_IMAGE="ubuntu-core-jammy"
#FROM s2ssolutions/$BASE_IMAGE:$BASE_TAG
USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/install
#WORKDIR $HOME
RUN grep -rl "kasm-user" $STARTUPDIR | xargs sed -i 's/kasm-user/temp-user/g'
######### Customize Container Here ###########


# Install Firefox
#COPY ./src/ubuntu/install/firefox/ $INST_SCRIPTS/firefox/
#COPY ./src/ubuntu/install/firefox/firefox.desktop $HOME/Desktop/
#RUN bash $INST_SCRIPTS/firefox/install_firefox.sh && rm -rf $INST_SCRIPTS/firefox/

# Update the desktop environment to be optimized for a single application
#RUN cp $HOME/.config/xfce4/xfconf/single-application-xfce-perchannel-xml/* $HOME/.config/xfce4/xfconf/xfce-perchannel-xml/
#RUN cp /usr/share/backgrounds/bg_kasm.png /usr/share/backgrounds/bg_default.png
#RUN apt-get remove -y xfce4-panel

# Security modifications
#COPY ./src/ubuntu/install/misc/single_app_security.sh $INST_SCRIPTS/misc/
#RUN  bash $INST_SCRIPTS/misc/single_app_security.sh -t && rm -rf $INST_SCRIPTS/misc/

# Setup the custom startup script that will be invoked when the container starts
#ENV LAUNCH_URL  http://kasmweb.com

COPY ./src/ubuntu/install/firefox/custom_startup.sh $STARTUPDIR/custom_startup.sh
RUN chmod +x $STARTUPDIR/custom_startup.sh

# Install Custom Certificate Authority
# COPY ./src/ubuntu/install/certificates $INST_SCRIPTS/certificates/
# RUN bash $INST_SCRIPTS/certificates/install_ca_cert.sh && rm -rf $INST_SCRIPTS/certificates/

#ENV KASM_RESTRICTED_FILE_CHOOSER=1
#COPY ./src/ubuntu/install/gtk/ $INST_SCRIPTS/gtk/
#RUN bash $INST_SCRIPTS/gtk/install_restricted_file_chooser.sh

### PRE INSTALL EXTENSIONS ###
COPY ./src/ubuntu/install/firefox/policies.json /etc/firefox/policies/policies.json

### REPLACE BG AND SQUID IMAGES ###
COPY ./src/common/resources/images/SN.png /usr/local/squid/share/icons/SN.png
RUN chown proxy:proxy /usr/local/squid/share/icons/SN.png

COPY ./src/common/resources/images/bg_kasm.png  /usr/share/backgrounds/bg_kasm.png
COPY ./src/common/resources/images/bg_kasm.png  /usr/share/backgrounds/bg_default.png
######### End Customizations ###########

RUN chown 1000:0 $HOME
RUN $STARTUPDIR/set_user_permission.sh $HOME

### CHANGE USER:GROUP NAME ###
ENV HOME /home/temp-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

RUN groupmod -n "temp-user" "kasm-user"
RUN usermod -l "temp-user" "kasm-user"
RUN usermod -d /home/"temp-user" "temp-user"
RUN rm -rf /home/kasm-user

### Apply baseline ff setup ###
COPY ./src/ubuntu/install/firefox/mozilla-backup.tar.gz /tmp/mozilla-backup.tar.gz
RUN tar -xvzf /tmp/mozilla-backup.tar.gz -C /home/temp-user/
RUN rm /tmp/mozilla-backup.tar.gz
RUN chown -R temp-user:temp-user $HOME/.mozilla

### Override default ua string ###
RUN echo 'user_pref("general.useragent.override", "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.1");' >> $HOME/.mozilla/firefox/kasm/prefs.js


USER 1000
