ARG BASE_TAG="develop"
ARG BASE_IMAGE="kali-rolling-desktop"
FROM kasmweb/$BASE_IMAGE:$BASE_TAG
USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
WORKDIR $HOME

### Replace kasm-user > temp-user in all startup scripts ###
RUN grep -rl "kasm-user" $STARTUPDIR | xargs sed -i 's/kasm-user/temp-user/g'

### Envrionment config
#ENV DEBIAN_FRONTEND=noninteractive \
#    SKIP_CLEAN=true \
#    KASM_RX_HOME=$STARTUPDIR/kasmrx \
#    DONT_PROMPT_WSL_INSTALL="No_Prompt_please" \
#    INST_DIR=$STARTUPDIR/install \
#    INST_SCRIPTS="/ubuntu/install/kali/install_kali.sh \
#                  /ubuntu/install/chromium/install_chromium.sh \
#                  /ubuntu/install/firefox/install_firefox.sh \
#                  /ubuntu/install/cleanup/cleanup.sh"

# Copy install scripts
#COPY ./src/ $INST_DIR

# Run installations
#RUN \
#  for SCRIPT in $INST_SCRIPTS; do \
#    bash ${INST_DIR}${SCRIPT} || exit 1; \
#  done && \
#  $STARTUPDIR/set_user_permission.sh $HOME && \
#  rm -f /etc/X11/xinit/Xclients && \
#  chown 1000:0 $HOME && \
#  mkdir -p /home/temp-user && \
#  chown -R 1000:0 /home/temp-user && \
#  rm -Rf ${INST_DIR}

# Userspace Runtime

#COPY ./src/ubuntu/install/chrome/custom_startup.sh $STARTUPDIR/custom_startup.sh
#RUN chmod +x $STARTUPDIR/custom_startup.sh

#COPY ./src/ubuntu/install/chrome/set_locale.sh $STARTUPDIR/set_locale.sh
#RUN chmod +x $STARTUPDIR/set_locale.sh

### REPLACE BG AND SQUID IMAGES ###
COPY ./src/common/resources/images/SN.png /usr/local/squid/share/icons/SN.png
RUN chown proxy:proxy /usr/local/squid/share/icons/SN.png

# Update kali PGP keys
RUN wget https://archive.kali.org/archive-keyring.gpg -O /usr/share/keyrings/kali-archive-keyring.gpg

### ADD active/passive recon tools ###
ENV DEBIAN_FRONTEND=noninteractive

# # Update and install CLI-based active and passive recon tools
RUN apt-get update && apt-get full-upgrade -y && apt-get install -y --no-install-recommends \
    python3.13-venv \
    python3-pip \
    pipx \
    tor \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN chown 1000:0 $HOME
RUN $STARTUPDIR/set_user_permission.sh $HOME

### CHANGE USER:GROUP NAME ###
ENV HOME /home/temp-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

RUN groupmod -n "temp-user" "kasm-user"
RUN usermod -l "temp-user" "kasm-user"
RUN usermod -d /home/"temp-user" "temp-user"
RUN rm -rf /home/kasm-user

### Add pwordless sudo ###
RUN echo "temp-user ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/temp-user && \
    chmod 0440 /etc/sudoers.d/temp-user

USER 1000

ENV PATH="$HOME/.local/bin:$PATH"

RUN pipx install playwright
# RUN /home/temp-user/.local/bin/playwright install
RUN playwright install

CMD ["--tail-log"]
